// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/account.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AccountService.Protos {
  /// <summary>
  /// Account Service to manage Bank Accounts
  /// </summary>
  public static partial class Account
  {
    static readonly string __ServiceName = "account.Account";

    static readonly grpc::Marshaller<global::AccountService.Protos.AccountRequest> __Marshaller_account_AccountRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AccountService.Protos.AccountRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AccountService.Protos.AccountReply> __Marshaller_account_AccountReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AccountService.Protos.AccountReply.Parser.ParseFrom);

    static readonly grpc::Method<global::AccountService.Protos.AccountRequest, global::AccountService.Protos.AccountReply> __Method_CheckBalance = new grpc::Method<global::AccountService.Protos.AccountRequest, global::AccountService.Protos.AccountReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckBalance",
        __Marshaller_account_AccountRequest,
        __Marshaller_account_AccountReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AccountService.Protos.AccountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Account</summary>
    [grpc::BindServiceMethod(typeof(Account), "BindService")]
    public abstract partial class AccountBase
    {
      /// <summary>
      /// Check Account Balance
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::AccountService.Protos.AccountReply> CheckBalance(global::AccountService.Protos.AccountRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Account</summary>
    public partial class AccountClient : grpc::ClientBase<AccountClient>
    {
      /// <summary>Creates a new client for Account</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AccountClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Account that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AccountClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AccountClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AccountClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Check Account Balance
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AccountService.Protos.AccountReply CheckBalance(global::AccountService.Protos.AccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckBalance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Check Account Balance
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AccountService.Protos.AccountReply CheckBalance(global::AccountService.Protos.AccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckBalance, null, options, request);
      }
      /// <summary>
      /// Check Account Balance
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AccountService.Protos.AccountReply> CheckBalanceAsync(global::AccountService.Protos.AccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckBalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Check Account Balance
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AccountService.Protos.AccountReply> CheckBalanceAsync(global::AccountService.Protos.AccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckBalance, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AccountClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AccountClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AccountBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CheckBalance, serviceImpl.CheckBalance).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AccountBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CheckBalance, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AccountService.Protos.AccountRequest, global::AccountService.Protos.AccountReply>(serviceImpl.CheckBalance));
    }

  }
}
#endregion
